export const ActionTypes = {
    APP: 'APP',

    LOGIN: 'LOGIN',
    UPDATE_CREDS: 'UPDATE_CREDS',
    LOGOUT: 'LOGOUT',

    UPDATE_RUNNING: 'UPDATE_RUNNING',
    UPDATE_BIKING: 'UPDATE_BIKING',
    UPDATE_SWIMMING: 'UPDATE_SWIMMING',
    UPDATE_CURLS: 'UPDATE_CURLS',
    UPDATE_BENCH_PRESS: 'UPDATE_BENCH_PRESS',
    UPDATE_DEAD_LIFT: 'UPDATE_DEAD_LIFT',
    UPDATE_SQUATS: 'UPDATE_SQUATS',
    UPDATE_PUSH_UPS: 'UPDATE_PUSH_UPS',
    UPDATE_PULL_UPS: 'UPDATE_PULL_UPS',
    UPDATE_SIT_UPS: 'UPDATE_SIT_UPS',
    SUBMIT_WORKOUTS: 'SUBMIT_WORKOUTS',

    UPDATE_USERNAME: 'UPDATE_USERNAME',
    UPDATE_PASSWORD: 'UPDATE_PASSWORD',
    UPDATE_NAME: 'UPDATE_NAME',
    UPDATE_EMAIL: 'UPDATE_EMAIL',
    UPDATE_ISPRIVATE: 'UPDATE_ISPRIVATE',
    SIGN_UP: 'SIGN_UP',

    TOGGLE_CONFIRM_MODAL: 'TOGGLE_CONFIRM_MODAL',

    // ALL USERS COMPONENT ACTION TYPES
    GET_USERS: 'GET_USERS',

    // Exercise CHART ACTION TYPES
    UPDATE_Exercise_CHART_COMPONENT_STATE: 'UPDATE_Exercise_COMPONENT_PROPS'
};